In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [6]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/PGSS-2021/L2792021/britishSeatBeltStudy.csv")
df.head()

   DriversKilled  drivers  front  rear    kms  PetrolPrice  VanKilled  law
0            107     1687    867   269   9059     0.102972         12    0
1             97     1508    825   265   7685     0.102363          6    0
2            102     1507    806   319   9963     0.102062         12    0
3             87     1385    814   407  10955     0.100873          8    0
4            119     1632    991   454  11823     0.101020         10    0

In [7]:
df["law"] = df["law"].astype("category")
df.info()
from sklearn.linear_model import LogisticRegression 
from sklearn import metrics

X=df[['DriversKilled', 'VanKilled']]  # Features
y=df['law'].astype('category')  # Labels

myModel = LogisticRegression()
myModel.fit(X,y)

y_pred = myModel.predict([[100, 10]])[0]
y_pred

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DriversKilled  192 non-null    int64
 1   drivers        192 non-null    int64
 2   front          192 non-null    int64
 3   rear           192 non-null    int64
 4   kms            192 non-null    int64
 5   PetrolPrice    192 non-null    float64
 6   VanKilled      192 non-null    int64
 7   law            192 non-null    category
dtypes: category(1), float64(1), int64(6)
memory usage: 10.9 KB

0